name: Test Linux AD Connector Scripts

on: [push, pull_request]

jobs:
  test-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bash realmd sssd adcli

      - name: Test AD install script
        run: |
          chmod +x JoinActiveDirectory.sh
          bash -n ./JoinActiveDirectory.sh

      - name: Test AD deinstall script
        run: |
          chmod +x LeaveActiveDirectory.sh
          bash -n ./LeaveActiveDirectory.sh
